apiVersion: v1
kind: Namespace
metadata:
  name: syndeno-collector

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: collector
  namespace: syndeno-collector

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syndeno-collector-cluster-role-web-monitor
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: syndeno-collector-cluster-bind-web-monitor
  namespace: syndeno-collector
subjects:
- kind: ServiceAccount
  name: collector
  namespace: syndeno-collector
roleRef:
  kind: ClusterRole
  name: syndeno-collector-cluster-role-web-monitor
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: syndeno-web-monitor
  labels:
    app: syndeno-web-monitor
    developer: danisyn
    language: go
    function: kubernetes-ingress-web-monitor
  namespace: syndeno-collector
spec:
  serviceName: syndeno-web-monitor
  replicas: 1
  selector:
    matchLabels:
      app: syndeno-web-monitor
  template:
    metadata:
      labels:
        app: syndeno-web-monitor
    spec:
      serviceAccountName: collector
      containers:
      - name: syndeno-web-monitor
        image: daniels7/ingress-monitor:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 300M 

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxDB
spec:
  selector:
    matchLabels:
      app: influxDB
  serviceName: influxDB
  replicas: 1
  template:
    metadata:
      labels:
        app: influxDB
    spec:
      containers:
      - name: influxDB
        image: influxdb:latest
        ports:
        - containerPort: 8086
          name: web
        env: 
          - name: DOCKER_INFLUXDB_INIT_MODE
            value: setup
          - name: DOCKER_INFLUXDB_INIT_USERNAME
            value: syndeno
          - name: DOCKER_INFLUXDB_INIT_PASSWORD
            value: Syndeno2022!
          - name: DOCKER_INFLUXDB_INIT_ORG
            value: syndeno
          - name: DOCKER_INFLUXDB_INIT_BUCKET
            value: my-bucket
          - name: DOCKER_INFLUXDB_INIT_RETENTION
            value: 1w
        volumeMounts:
        - name: influxdb-data
          mountPath: /var/lib/influxdb2
  volumeClaimTemplates:
  - metadata:
      name: influxdb-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
